/**
 * Word Document Generator for ILPA Notices
 *
 * Generates .docx files for capital calls and distributions
 * using the docx library.
 *
 * IMPORTANT: Requires 'docx' package to be installed:
 * npm install docx
 */

import {
  Document,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
  WidthType,
  convertInchesToTwip,
  PageBreak,
  Header,
  Footer,
} from 'docx'
import type { CapitalCall, CapitalCallAllocation, Distribution, DistributionAllocation } from './types'
import { formatCurrencyDetailed } from '@/lib/format-utils'

// Polibit brand colors
const BRAND_COLORS = {
  primary: '2D1B69',      // Dark purple
  secondary: '6B5B95',    // Light purple
  text: '333333',
  muted: '666666',
}

// Document options
export interface DocxGeneratorOptions {
  firmName?: string
  firmLogo?: string       // Base64 encoded image
  includeFooter?: boolean
  includeBankDetails?: boolean
  bankDetails?: {
    bankName: string
    accountName: string
    accountNumber: string
    routingNumber?: string
    swiftCode?: string
    clabe?: string
    reference?: string
  }
}

/**
 * Generate Capital Call Notice as Word document
 */
export async function generateCapitalCallDocx(
  capitalCall: CapitalCall,
  allocations: CapitalCallAllocation[],
  options: DocxGeneratorOptions = {}
): Promise<Uint8Array> {
  const { firmName = 'Investment Manager' } = options

  const doc = new Document({
    creator: firmName,
    title: `Capital Call Notice #${capitalCall.callNumber}`,
    description: `ILPA-compliant capital call notice for ${capitalCall.fundName}`,
    styles: {
      paragraphStyles: [
        {
          id: 'Normal',
          name: 'Normal',
          run: {
            font: 'Calibri',
            size: 22, // 11pt
            color: BRAND_COLORS.text,
          },
        },
      ],
    },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: convertInchesToTwip(1),
              bottom: convertInchesToTwip(1),
              left: convertInchesToTwip(1),
              right: convertInchesToTwip(1),
            },
          },
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: firmName,
                    bold: true,
                    size: 24,
                    color: BRAND_COLORS.primary,
                  }),
                ],
                alignment: AlignmentType.RIGHT,
              }),
            ],
          }),
        },
        footers: options.includeFooter !== false ? {
          default: new Footer({
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: 'This notice is generated by Polibit Investment Management Platform',
                    size: 16,
                    color: BRAND_COLORS.muted,
                  }),
                ],
                alignment: AlignmentType.CENTER,
              }),
            ],
          }),
        } : undefined,
        children: [
          // Title
          new Paragraph({
            children: [
              new TextRun({
                text: 'CAPITAL CALL NOTICE',
                bold: true,
                size: 32,
                color: BRAND_COLORS.primary,
              }),
            ],
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
          }),

          // Notice Number and Date
          new Paragraph({
            children: [
              new TextRun({
                text: `Notice #${capitalCall.callNumber}`,
                bold: true,
                size: 24,
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 },
          }),

          // Section A: Fund Information
          createSectionHeading('Section A: Fund Information'),
          createInfoTable([
            ['Fund Name', capitalCall.fundName],
            ['Call Date', formatDate(capitalCall.callDate)],
            ['Due Date', formatDate(capitalCall.dueDate)],
            ['Total Call Amount', formatCurrency(capitalCall.totalCallAmount, capitalCall.currency)],
            ['Purpose', capitalCall.purpose],
          ]),

          new Paragraph({ spacing: { before: 400 } }),

          // Section B: Investor Allocations
          createSectionHeading('Section B: Investor Allocations'),
          createAllocationTable(allocations, capitalCall.currency),

          new Paragraph({ spacing: { before: 400 } }),

          // Section C: Payment Instructions (if bank details provided)
          ...(options.includeBankDetails !== false && options.bankDetails
            ? [
                createSectionHeading('Section C: Payment Instructions'),
                createInfoTable([
                  ['Bank Name', options.bankDetails.bankName],
                  ['Account Name', options.bankDetails.accountName],
                  ['Account Number', options.bankDetails.accountNumber],
                  ...(options.bankDetails.routingNumber
                    ? [['Routing Number', options.bankDetails.routingNumber] as [string, string]]
                    : []),
                  ...(options.bankDetails.swiftCode
                    ? [['SWIFT Code', options.bankDetails.swiftCode] as [string, string]]
                    : []),
                  ...(options.bankDetails.clabe
                    ? [['CLABE', options.bankDetails.clabe] as [string, string]]
                    : []),
                  ['Reference', options.bankDetails.reference || `Capital Call #${capitalCall.callNumber}`],
                ]),
              ]
            : []),

          new Paragraph({ spacing: { before: 400 } }),

          // Section D: Terms and Conditions
          createSectionHeading('Section D: Important Information'),
          new Paragraph({
            children: [
              new TextRun({
                text: `Please ensure payment is received by ${formatDate(capitalCall.dueDate)}. `,
                size: 22,
              }),
              new TextRun({
                text: 'Late payments may be subject to penalties as outlined in the partnership agreement.',
                size: 22,
              }),
            ],
            spacing: { after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: 'If you have any questions regarding this capital call, please contact your investor relations representative.',
                size: 22,
              }),
            ],
          }),
        ],
      },
    ],
  })

  return await Packer.toBuffer(doc)
}

/**
 * Generate Individual LP Capital Call Notice
 */
export async function generateIndividualCapitalCallDocx(
  capitalCall: CapitalCall,
  allocation: CapitalCallAllocation,
  options: DocxGeneratorOptions = {}
): Promise<Uint8Array> {
  const { firmName = 'Investment Manager' } = options

  const doc = new Document({
    creator: firmName,
    title: `Capital Call Notice #${capitalCall.callNumber} - ${allocation.investorName}`,
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: convertInchesToTwip(1),
              bottom: convertInchesToTwip(1),
              left: convertInchesToTwip(1),
              right: convertInchesToTwip(1),
            },
          },
        },
        children: [
          // Title
          new Paragraph({
            children: [
              new TextRun({
                text: 'CAPITAL CALL NOTICE',
                bold: true,
                size: 32,
                color: BRAND_COLORS.primary,
              }),
            ],
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
          }),

          // Recipient
          new Paragraph({
            children: [
              new TextRun({ text: 'To: ', bold: true, size: 24 }),
              new TextRun({ text: allocation.investorName, size: 24 }),
            ],
            spacing: { after: 200 },
          }),

          // Fund and Call Info
          createSectionHeading('Capital Call Details'),
          createInfoTable([
            ['Fund Name', capitalCall.fundName],
            ['Call Number', `#${capitalCall.callNumber}`],
            ['Call Date', formatDate(capitalCall.callDate)],
            ['Due Date', formatDate(capitalCall.dueDate)],
            ['Purpose', capitalCall.purpose],
          ]),

          new Paragraph({ spacing: { before: 400 } }),

          // Your Allocation
          createSectionHeading('Your Allocation'),
          createInfoTable([
            ['Commitment', formatCurrency(allocation.commitment, capitalCall.currency)],
            ['Ownership Percentage', `${allocation.ownershipPercent.toFixed(4)}%`],
            ['Call Amount', formatCurrency(allocation.callAmount, capitalCall.currency)],
            ['Called Capital to Date', formatCurrency(allocation.calledCapitalToDate, capitalCall.currency)],
            ['Remaining Uncalled', formatCurrency(allocation.uncalledCapital, capitalCall.currency)],
          ]),

          new Paragraph({ spacing: { before: 400 } }),

          // Payment Summary
          createSectionHeading('Amount Due'),
          new Paragraph({
            children: [
              new TextRun({
                text: formatCurrency(allocation.callAmount, capitalCall.currency),
                bold: true,
                size: 36,
                color: BRAND_COLORS.primary,
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { before: 200, after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Due by: ${formatDate(capitalCall.dueDate)}`,
                size: 24,
              }),
            ],
            alignment: AlignmentType.CENTER,
          }),

          // Bank Details
          ...(options.includeBankDetails !== false && options.bankDetails
            ? [
                new Paragraph({ spacing: { before: 400 } }),
                createSectionHeading('Payment Instructions'),
                createInfoTable([
                  ['Bank Name', options.bankDetails.bankName],
                  ['Account Name', options.bankDetails.accountName],
                  ['Account Number', options.bankDetails.accountNumber],
                  ...(options.bankDetails.clabe
                    ? [['CLABE', options.bankDetails.clabe] as [string, string]]
                    : []),
                  ['Reference', `CC${capitalCall.callNumber}-${allocation.investorId.slice(0, 8)}`],
                ]),
              ]
            : []),
        ],
      },
    ],
  })

  return await Packer.toBuffer(doc)
}

/**
 * Generate Distribution Notice as Word document
 */
export async function generateDistributionDocx(
  distribution: Distribution,
  allocations: DistributionAllocation[],
  options: DocxGeneratorOptions = {}
): Promise<Uint8Array> {
  const { firmName = 'Investment Manager' } = options

  const doc = new Document({
    creator: firmName,
    title: `Distribution Notice #${distribution.distributionNumber}`,
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: convertInchesToTwip(1),
              bottom: convertInchesToTwip(1),
              left: convertInchesToTwip(1),
              right: convertInchesToTwip(1),
            },
          },
        },
        children: [
          // Title
          new Paragraph({
            children: [
              new TextRun({
                text: 'DISTRIBUTION NOTICE',
                bold: true,
                size: 32,
                color: BRAND_COLORS.primary,
              }),
            ],
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
          }),

          // Notice Number
          new Paragraph({
            children: [
              new TextRun({
                text: `Distribution #${distribution.distributionNumber}`,
                bold: true,
                size: 24,
              }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 },
          }),

          // Section A: Distribution Information
          createSectionHeading('Section A: Distribution Information'),
          createInfoTable([
            ['Fund Name', distribution.fundName],
            ['Distribution Date', formatDate(distribution.distributionDate)],
            ['Payment Date', formatDate(distribution.paymentDate)],
            ['Total Distribution', formatCurrency(distribution.totalDistributionAmount, distribution.currency)],
            ['Source', distribution.source],
          ]),

          new Paragraph({ spacing: { before: 400 } }),

          // Section B: Tax Classification
          createSectionHeading('Section B: Tax Classification'),
          createInfoTable([
            ['Return of Capital', distribution.isReturnOfCapital ? 'Yes' : 'No'],
            ['Income', distribution.isIncome ? 'Yes' : 'No'],
            ['Capital Gain', distribution.isCapitalGain ? 'Yes' : 'No'],
          ]),

          new Paragraph({ spacing: { before: 400 } }),

          // Section C: Investor Allocations
          createSectionHeading('Section C: Investor Allocations'),
          createDistributionAllocationTable(allocations, distribution.currency),
        ],
      },
    ],
  })

  return await Packer.toBuffer(doc)
}

// Helper functions

function createSectionHeading(text: string): Paragraph {
  return new Paragraph({
    children: [
      new TextRun({
        text,
        bold: true,
        size: 26,
        color: BRAND_COLORS.secondary,
      }),
    ],
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 300, after: 200 },
    border: {
      bottom: {
        color: BRAND_COLORS.secondary,
        size: 1,
        style: BorderStyle.SINGLE,
      },
    },
  })
}

function createInfoTable(rows: [string, string][]): Table {
  return new Table({
    width: {
      size: 100,
      type: WidthType.PERCENTAGE,
    },
    rows: rows.map(
      ([label, value]) =>
        new TableRow({
          children: [
            new TableCell({
              children: [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: label,
                      bold: true,
                      size: 22,
                      color: BRAND_COLORS.muted,
                    }),
                  ],
                }),
              ],
              width: { size: 30, type: WidthType.PERCENTAGE },
              borders: {
                top: { style: BorderStyle.NONE },
                bottom: { style: BorderStyle.NONE },
                left: { style: BorderStyle.NONE },
                right: { style: BorderStyle.NONE },
              },
            }),
            new TableCell({
              children: [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: value,
                      size: 22,
                    }),
                  ],
                }),
              ],
              width: { size: 70, type: WidthType.PERCENTAGE },
              borders: {
                top: { style: BorderStyle.NONE },
                bottom: { style: BorderStyle.NONE },
                left: { style: BorderStyle.NONE },
                right: { style: BorderStyle.NONE },
              },
            }),
          ],
        })
    ),
  })
}

function createAllocationTable(allocations: CapitalCallAllocation[], currency: string): Table {
  const headerRow = new TableRow({
    children: ['Investor', 'Commitment', 'Ownership %', 'Call Amount', 'Status'].map(
      (text) =>
        new TableCell({
          children: [
            new Paragraph({
              children: [
                new TextRun({
                  text,
                  bold: true,
                  size: 20,
                  color: 'FFFFFF',
                }),
              ],
              alignment: AlignmentType.CENTER,
            }),
          ],
          shading: { fill: BRAND_COLORS.primary },
        })
    ),
  })

  const dataRows = allocations.map(
    (alloc) =>
      new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: alloc.investorName, size: 20 })] })],
          }),
          new TableCell({
            children: [
              new Paragraph({
                children: [new TextRun({ text: formatCurrency(alloc.commitment, currency), size: 20 })],
                alignment: AlignmentType.RIGHT,
              }),
            ],
          }),
          new TableCell({
            children: [
              new Paragraph({
                children: [new TextRun({ text: `${alloc.ownershipPercent.toFixed(2)}%`, size: 20 })],
                alignment: AlignmentType.CENTER,
              }),
            ],
          }),
          new TableCell({
            children: [
              new Paragraph({
                children: [new TextRun({ text: formatCurrency(alloc.callAmount, currency), size: 20 })],
                alignment: AlignmentType.RIGHT,
              }),
            ],
          }),
          new TableCell({
            children: [
              new Paragraph({
                children: [new TextRun({ text: alloc.status, size: 20 })],
                alignment: AlignmentType.CENTER,
              }),
            ],
          }),
        ],
      })
  )

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [headerRow, ...dataRows],
  })
}

function createDistributionAllocationTable(allocations: DistributionAllocation[], currency: string): Table {
  const headerRow = new TableRow({
    children: ['Investor', 'Ownership %', 'Base Allocation', 'Final Allocation', 'Status'].map(
      (text) =>
        new TableCell({
          children: [
            new Paragraph({
              children: [
                new TextRun({
                  text,
                  bold: true,
                  size: 20,
                  color: 'FFFFFF',
                }),
              ],
              alignment: AlignmentType.CENTER,
            }),
          ],
          shading: { fill: BRAND_COLORS.primary },
        })
    ),
  })

  const dataRows = allocations.map(
    (alloc) =>
      new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: alloc.investorName, size: 20 })] })],
          }),
          new TableCell({
            children: [
              new Paragraph({
                children: [new TextRun({ text: `${alloc.ownershipPercent.toFixed(2)}%`, size: 20 })],
                alignment: AlignmentType.CENTER,
              }),
            ],
          }),
          new TableCell({
            children: [
              new Paragraph({
                children: [new TextRun({ text: formatCurrency(alloc.baseAllocation, currency), size: 20 })],
                alignment: AlignmentType.RIGHT,
              }),
            ],
          }),
          new TableCell({
            children: [
              new Paragraph({
                children: [new TextRun({ text: formatCurrency(alloc.finalAllocation, currency), size: 20 })],
                alignment: AlignmentType.RIGHT,
              }),
            ],
          }),
          new TableCell({
            children: [
              new Paragraph({
                children: [new TextRun({ text: alloc.status, size: 20 })],
                alignment: AlignmentType.CENTER,
              }),
            ],
          }),
        ],
      })
  )

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [headerRow, ...dataRows],
  })
}

function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

function formatCurrency(amount: number, currency: string = 'USD'): string {
  return formatCurrencyDetailed(amount, currency)
}

/**
 * Download Word document (browser)
 */
export function downloadDocx(buffer: Uint8Array, filename: string): void {
  const blob = new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  })
  const url = URL.createObjectURL(blob)

  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
