import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { generateILPAPDFData, ILPAReportConfig } from './ilpa-report-generator'

export async function generateILPAPDF(config: ILPAReportConfig, firmName: string = 'Investment Manager'): Promise<Buffer> {
  const pdf = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  })

  const data = generateILPAPDFData(config)

  // Page 1: Cover Page
  pdf.setFontSize(24)
  pdf.setFont('helvetica', 'bold')
  pdf.text('ILPA Portfolio Company Metrics Template', pdf.internal.pageSize.getWidth() / 2, 30, { align: 'center' })

  pdf.setFontSize(16)
  pdf.text('Version 1.0', pdf.internal.pageSize.getWidth() / 2, 40, { align: 'center' })

  pdf.setFontSize(12)
  pdf.setFont('helvetica', 'normal')
  pdf.text(`Generated by ${firmName}`, pdf.internal.pageSize.getWidth() / 2, 50, { align: 'center' })

  // Fund Information
  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Fund Information', 20, 70)

  pdf.setFontSize(11)
  pdf.setFont('helvetica', 'normal')
  const fundInfo = [
    ['GP Name:', config.gpName],
    ['Fund Name:', config.fundName],
    ['Reporting Date:', new Date(config.reportingDate).toLocaleDateString()],
    ['Fund Currency:', config.fundCurrency],
    ['Total Investments:', data.summary.totalInvestments.toString()],
  ]

  let yPosition = 80
  fundInfo.forEach(([label, value]) => {
    pdf.setFont('helvetica', 'bold')
    pdf.text(label, 20, yPosition)
    pdf.setFont('helvetica', 'normal')
    pdf.text(value, 70, yPosition)
    yPosition += 8
  })

  // Summary Metrics
  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Portfolio Summary', 20, yPosition + 10)

  yPosition += 20
  const summaryData = [
    ['Total Committed:', `${config.fundCurrency} ${data.summary.totalCommitted.toLocaleString()}`],
    ['Total Value:', `${config.fundCurrency} ${data.summary.totalValue.toLocaleString()}`],
    ['Total Realized:', `${config.fundCurrency} ${data.summary.totalRealized.toLocaleString()}`],
    ['Weighted Avg IRR:', `${data.summary.weightedAvgIRR.toFixed(2)}%`],
    ['Weighted Avg Multiple:', `${data.summary.weightedAvgMultiple.toFixed(2)}x`],
  ]

  summaryData.forEach(([label, value]) => {
    pdf.setFont('helvetica', 'bold')
    pdf.text(label, 20, yPosition)
    pdf.setFont('helvetica', 'normal')
    pdf.text(value, 70, yPosition)
    yPosition += 8
  })

  // Page 2: Portfolio Company Details
  pdf.addPage()
  pdf.setFontSize(16)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Portfolio Company Details', 20, 20)

  // Create table with investment data
  const tableData = data.investments.map(inv => [
    inv.position,
    inv.positionStatus,
    inv.positionTypeCurrent,
    inv.naicsSector,
    `${config.fundCurrency} ${inv.totalInvestedFund.toLocaleString()}`,
    `${inv.fullyDilutedOwnershipFund.toFixed(2)}%`,
    `${config.fundCurrency} ${inv.reportedValue.toLocaleString()}`,
    `${inv.grossIRR.toFixed(2)}%`,
    `${inv.multipleTotalReturn.toFixed(2)}x`,
    inv.hqCountry,
  ])

  autoTable(pdf, {
    startY: 30,
    head: [[
      'Position',
      'Status',
      'Type',
      'Sector',
      'Invested',
      'Ownership',
      'Value',
      'IRR',
      'Multiple',
      'Country'
    ]],
    body: tableData,
    styles: {
      fontSize: 8,
      cellPadding: 2,
    },
    headStyles: {
      fillColor: [66, 139, 202],
      textColor: 255,
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245],
    },
    margin: { left: 10, right: 10 },
  })

  // Page 3: Detailed Investment Information
  data.investments.forEach((inv, index) => {
    pdf.addPage()
    pdf.setFontSize(14)
    pdf.setFont('helvetica', 'bold')
    pdf.text(`Investment ${index + 1}: ${inv.position}`, 20, 20)

    let y = 35

    // Basic Information
    pdf.setFontSize(12)
    pdf.text('Basic Information', 20, y)
    y += 8

    pdf.setFontSize(10)
    const basicInfo = [
      ['Position Identifier:', inv.positionIdentifier],
      ['Position Status:', inv.positionStatus],
      ['Company Currency:', inv.companyReportingCurrency],
      ['Position Type:', inv.positionTypeCurrent],
      ['NAICS Sector:', inv.naicsSector],
    ]

    basicInfo.forEach(([label, value]) => {
      pdf.setFont('helvetica', 'bold')
      pdf.text(label, 20, y)
      pdf.setFont('helvetica', 'normal')
      pdf.text(value, 80, y)
      y += 7
    })

    // Transaction Details
    y += 5
    pdf.setFontSize(12)
    pdf.setFont('helvetica', 'bold')
    pdf.text('Transaction Details', 20, y)
    y += 8

    pdf.setFontSize(10)
    const transactionInfo = [
      ['Initial Investment Date:', inv.initialInvestmentDate],
      ['Investment Strategy:', inv.investmentStrategy],
      ['Purchase Process:', inv.purchaseProcess],
      ['Deal Role:', inv.dealRole],
    ]

    transactionInfo.forEach(([label, value]) => {
      pdf.setFont('helvetica', 'bold')
      pdf.text(label, 20, y)
      pdf.setFont('helvetica', 'normal')
      pdf.text(value, 80, y)
      y += 7
    })

    // Financial Metrics
    y += 5
    pdf.setFontSize(12)
    pdf.setFont('helvetica', 'bold')
    pdf.text('Financial Metrics', 20, y)
    y += 8

    pdf.setFontSize(10)
    const financialInfo = [
      ['Total Invested (Fund):', `${config.fundCurrency} ${inv.totalInvestedFund.toLocaleString()}`],
      ['Ownership %:', `${inv.fullyDilutedOwnershipFund.toFixed(2)}%`],
      ['Total Enterprise Value:', `${config.fundCurrency} ${inv.totalEnterpriseValueEntry.toLocaleString()}`],
      ['Reported Value:', `${config.fundCurrency} ${inv.reportedValue.toLocaleString()}`],
      ['Realized Proceeds:', `${config.fundCurrency} ${inv.realizedProceeds.toLocaleString()}`],
    ]

    financialInfo.forEach(([label, value]) => {
      pdf.setFont('helvetica', 'bold')
      pdf.text(label, 20, y)
      pdf.setFont('helvetica', 'normal')
      pdf.text(value, 80, y)
      y += 7
    })

    // Performance Metrics
    y += 5
    pdf.setFontSize(12)
    pdf.setFont('helvetica', 'bold')
    pdf.text('Performance Metrics', 20, y)
    y += 8

    pdf.setFontSize(10)
    const performanceInfo = [
      ['Gross IRR:', `${inv.grossIRR.toFixed(2)}%`],
      ['Multiple (Total Return):', `${inv.multipleTotalReturn.toFixed(2)}x`],
      ['Multiple (Realizations):', `${inv.multipleRealizations.toFixed(2)}x`],
      ['Multiple (Unrealized):', `${inv.multipleUnrealized.toFixed(2)}x`],
    ]

    performanceInfo.forEach(([label, value]) => {
      pdf.setFont('helvetica', 'bold')
      pdf.text(label, 20, y)
      pdf.setFont('helvetica', 'normal')
      pdf.text(value, 80, y)
      y += 7
    })

    // Geographic Information
    if (y < 180) {
      y += 5
      pdf.setFontSize(12)
      pdf.setFont('helvetica', 'bold')
      pdf.text('Geographic Information', 20, y)
      y += 8

      pdf.setFontSize(10)
      const geoInfo = [
        ['HQ Country:', inv.hqCountry],
        ['Primary Market:', inv.primaryMarket],
        ['Country of Incorporation:', inv.countryOfIncorporation],
      ]

      geoInfo.forEach(([label, value]) => {
        pdf.setFont('helvetica', 'bold')
        pdf.text(label, 20, y)
        pdf.setFont('helvetica', 'normal')
        pdf.text(value, 80, y)
        y += 7
      })
    }

    // Company Description
    if (inv.companyDescription && y < 160) {
      y += 5
      pdf.setFontSize(12)
      pdf.setFont('helvetica', 'bold')
      pdf.text('Company Description', 20, y)
      y += 8

      pdf.setFontSize(9)
      pdf.setFont('helvetica', 'normal')
      const splitDescription = pdf.splitTextToSize(inv.companyDescription, 250)
      pdf.text(splitDescription, 20, y)
    }

    // Footer
    pdf.setFontSize(8)
    pdf.setFont('helvetica', 'italic')
    pdf.text(
      `ILPA Portfolio Company Metrics Template v1.0 - Page ${pdf.internal.pages.length - 1}`,
      pdf.internal.pageSize.getWidth() / 2,
      pdf.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    )
  })

  // Add footer to all pages
  const pageCount = pdf.internal.pages.length - 1
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i)
    pdf.setFontSize(8)
    pdf.setFont('helvetica', 'normal')
    pdf.text(
      `Generated on ${new Date().toLocaleDateString()} | ${firmName}`,
      pdf.internal.pageSize.getWidth() - 20,
      pdf.internal.pageSize.getHeight() - 10,
      { align: 'right' }
    )
  }

  // Convert to buffer
  const pdfBuffer = Buffer.from(pdf.output('arraybuffer'))
  return pdfBuffer
}
